### ISSUE TITLE
Bluetooth conflict with neopixel

### ISSUE THREAD

**Issue by faridskyman** [CytronTechnologies/pxt-rekabit#2]
Hi need help, after i add rekabit extension, in makecode(block) mode, I can't get Bluetooth to work as makecode  block editor says there is conflict between (bluetooth and NeoPixel)

Actual message

> Extensions 'neopixel' and 'bluetooth' cannot be used together, because they use incompatible settings (microbit-dal.bluetooth.enabled).

I decided to fork this repo, and modify files and remove the dependencies for neopixel, (i did it) but when i added the extension, neopixel still shows in the list of items, 

i have spend the entire day double forking this repo, made so much changes, for your ref:
* https://github.com/faridskyman/pxt-mod-rekabit-two

dont seem to work, when i added my forked-cloned git as i add extension, it will show up "rekabit" & "neopixel" and when i add bluetooth, i get the error.

im trying to make a car move, controlled via bluetooth, with rekabit, so far rekabit has been good, but this is stalling my plans, hope u guys have a solution, thank you

**Comment by faridskyman** [comment]
found the issue, 
1. i had to remove (radio and dependancy for neopixel and radio
2. i have to create a tag
3. i have to create a release, 

as makecore will get latest release, and when i fork, if i dont create a release, it takes the last release which is what u guys did, so that why it did not work. 
this video really help
https://www.youtube.com/watch?v=ztrm4XehfGo

so if any of you need my modified (rekabit extension) here is the link
https://github.com/faridskyman/pxt-rekabit

do note, it only has (motor and servos) and nothing else, cos i had to remove them to make bluetooth to work..
enjoy

**Comment by faridskyman** [comment]
issue solved

**Comment by kiate** [comment]
Sorry for the late reply. Glad that you've solved the issue!
Thank you so much for working on the modification so that Bluetooth blocks can be used on REKA:BIT. We'll definitely share your work when there's similar request from REKA:BIT users. Appreciate that!
